{{- if .Values.enabledPSP }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "app.fullname" . }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  - hostPath
  allowedHostPaths:
    - pathPrefix: /
      readOnly: true
{{- if .Values.enabledHostNetwork }}
  hostNetwork: true
  hostPorts:
  - min: {{ .Values.ports.metrics.port }}
    max: {{ .Values.ports.metrics.port }}
{{- end }}
{{- if .Values.enabledHostPID }}
  hostPID: true
{{- end }}
{{- end }}