{{- if .Values.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: expose-kube-etcd-metrics
subsets:
- addresses:
  {{- range .Values.endpoints }}
  - ip: {{ . }}
  {{- end }}
  ports:
  - name: {{ .Values.ports.metrics.name }}
    port: {{ .Values.ports.metrics.port }}
    protocol: {{ .Values.ports.metrics.protocol }}
{{- end }}
