apiVersion: {{ template "daemonset_api_version" . }}
kind: DaemonSet
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: exporter-node-binary-copy
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
        - pwsh
        - -f
        - c:/scripts/copy-binary.ps1
        {{- if and .Values.resources .Values.resources.inits }}
        resources:
{{ toYaml .Values.resources.inits | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: binary-host-path
          mountPath: c:/host/etc/wmi-exporter
        - name: exporter-scripts
          mountPath: c:/scripts/
      containers:
      - name: exporter-node
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
{{- if .Values.args }}
        args: {{ .Values.args }}
{{ end }}
        ports:
        - name: http
          containerPort: {{ .Values.ports.metrics.port }}
        env:
        - name: LISTEN_PORT
          value: "{{ .Values.ports.metrics.port }}"
{{- if .Values.enabledCollectors }}
        - name: ENABLED_COLLECTORS
          value: {{ .Values.enabledCollectors }}
{{- end }}
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 10 }}
        {{- end }}
        {{- if and .Values.resources .Values.resources.core }}
        resources:
{{ toYaml .Values.resources.core | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: wins-pipe
          mountPath: \\.\pipe\rancher_wins
      {{- if .Values.enabledRBAC }}
      serviceAccountName: {{ default (include "app.fullname" .) .Values.serviceAccountName }}
      {{- end }}
      tolerations:
      - operator: Exists
      nodeSelector:
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion }}
        beta.kubernetes.io/os: windows
{{- else}}
        kubernetes.io/os: windows
{{- end}}
        {{- range .Values.nodeSelectors }}
        {{- $pair := regexSplit "=" . 2 }}
        {{- if eq 2 (len $pair) }}
        {{ (index $pair 0) }}: {{ (index $pair 1) }}
        {{- else }}
        {{ (index $pair 0) }}: ""
        {{- end }}
        {{- end }}
      volumes:
      - name: wins-pipe
        hostPath:
          path: \\.\pipe\rancher_wins
      - name: binary-host-path
        hostPath:
          path: c:/etc/wmi-exporter
          type: DirectoryOrCreate
      - name: exporter-scripts
        configMap:
          name: {{ template "app.fullname" . }}
