apiVersion: v1
kind: Service
metadata:
  name:   expose-node-metrics-windows
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{ .Values.apiGroup }}: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: {{ .Values.ports.metrics.name }}
    port: {{ .Values.ports.metrics.port }}
    targetPort: {{ .Values.ports.metrics.port }}
    protocol: {{ .Values.ports.metrics.protocol }}
