apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: windows-node-recording-rules
    source: rancher-monitoring
  name: windows-node-recording-rules
  namespace: cattle-prometheus
spec:
  groups:
  - name: windows-cpu-recording.rules
    rules:
    - record: node_cpu_seconds_total
      expr: wmi_cpu_time_total
    - record: node_load1
      expr: avg_over_time(wmi_system_processor_queue_length[1m])
    - record: node_load5
      expr: avg_over_time(wmi_system_processor_queue_length[5m])
    - record: node_load15
      expr: avg_over_time(wmi_system_processor_queue_length[15m])
    - record: node_load15
      expr: avg_over_time(wmi_system_processor_queue_length[15m])
  - name: windows-memory-recording.rules
    rules:
    - record: node_memory_MemAvailable_bytes
      expr: wmi_os_physical_memory_free_bytes
    - record: node_memory_MemTotal_bytes
      expr: wmi_cs_physical_memory_bytes
  - name: windows-network-io-recording.rules
    rules:
    - record: node_network_receive_bytes_total
      expr: wmi_net_bytes_received_total
    - record: node_network_transmit_bytes_total
      expr: wmi_net_bytes_sent_total
  - name: windows-network-packet-recording.rules
    rules:
    - record: node_network_receive_packets_total
      expr: wmi_net_packets_received_total
    - record: node_network_transmit_packets_total
      expr: wmi_net_packets_sent_total
    - record: node_network_receive_drop_total
      expr: wmi_net_packets_received_discarded
    - record: node_network_receive_errs_total
      expr: wmi_net_packets_received_errors
    - record: node_network_transmit_drop_total
      expr: wmi_net_packets_outbound_discarded
  - name: windows-disk-io-recording.rules
    rules:
    - record: node_disk_written_bytes_total
      expr: wmi_logical_disk_write_bytes_total
    - record: node_disk_read_bytes_total
      expr: wmi_logical_disk_read_bytes_total
  - name: windows-file-usage-recording.rules
    rules:
    - record: node_filesystem_size_bytes
      expr: wmi_logical_disk_size_bytes
    - record: node_filesystem_free_bytes
      expr: wmi_logical_disk_free_bytes