apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{- include "webhook-receiver.labels" . | nindent 4 }}
  name: {{ template "app.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: webhook-receiver
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
        - /webhook-receiver
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /state
            port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
        ports:
        - containerPort: {{ .Values.port }}
        volumeMounts:
        - name: config
          mountPath: /etc/webhook-receiver
{{- if .Values.affinity }}
        affinity:
{{ toYaml .Values.affinity | indent 10 }}
{{- end }}
{{- if .Values.nodeSelector }}
        nodeSelector:
{{ toYaml .Values.nodeSelector | indent 10 }}
{{- end }}
{{- if .Values.tolerations }}
        tolerations:
{{ toYaml .Values.tolerations | indent 10 }}
{{- end }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
      volumes:
      - name: config
        secret:
          secretName: webhook-receiver
