apiVersion: v1
kind: Secret
metadata:
  name: webhook-receiver
  labels:
{{- include "webhook-receiver.labels" . | nindent 4 }}
data:
  config.yaml: {{ toYaml ( required "you must provide config for init" .Values.config ) | b64enc }}
