apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
  labels:
{{- include "webhook-receiver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
