{{- if (include "additional-scrape-configs.yaml" .) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}-additional-scrape-configs
stringData:
  additional-scrape-configs.yaml: {{ template "additional-scrape-configs.yaml" . }}
{{- end }}

{{- if (include "additional-alertmanager-configs.yaml" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}-additional-alertmanager-configs
stringData:
  additional-alertmanager-configs.yaml: {{ template "additional-alertmanager-configs.yaml" . }}
{{- end }}

{{- if .Values.thanos.enabled }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.thanos.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
stringData:
  thanos.yaml: |-
{{ toYaml .Values.thanos.objectConfig | indent 6 }}
{{- end }}
