enabledRBAC: true

## Tolerations for use with node taints
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
  #  - key: "key"
  #    operator: "Equal"
  #    value: "value"
  #    effect: "NoSchedule"

## Default liveness probe
##
defaultLivenessProbe:
  initialDelaySeconds: 100
  failureThreshold: 6
  httpGet:
    path: /
    port: 8080
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 30

## Default readiness probe
##
defaultReadinessProbe:
  initialDelaySeconds: 10
  failureThreshold: 6
  httpGet:
    path: /
    port: 8080
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5
