{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: {{ template "rbac_api_version" . }}
metadata:
  name: {{ template "fluentd-tester.fullname" . }}
  labels:
    app: {{ template "fluentd-tester.name" . }}
    chart: {{ template "fluentd-tester.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd-tester.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "fluentd-tester.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
