{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: {{ template "rbac_api_version" . }}
metadata:
  name: {{ template "fluentd-tester.fullname" . }}
  labels:
    app: {{ template "fluentd-tester.name" . }}
    chart: {{ template "fluentd-tester.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
{{- end -}}