apiVersion: v1
description: Rancher logging helm chart to support logging function in rancher
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
name: rancher-logging
version: 0.3.0
appVersion: 1.6.3
home: https://www.fluentd.org/
sources:
  - https://www.fluentd.org/
maintainers:
  - name: Michelia
    email: support@rancher.com
kubeVersion: <1.21
