{
 "title": "Cluster",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(node_boot_time_seconds, node)"
   }
  ]
 },
 "panels": [
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage (2m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{node=~\"^$Node$\"}) * 100",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[2m])) by (node) / sum (machine_cpu_cores) by (node) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"}) * 100",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) by (node) / sum (machine_memory_bytes) by (node) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) * 100",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"}) by (node) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$Node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$Node\"})"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\".*\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\".*\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Jobs Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\".*\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\".*\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 40 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\".*\", node=~\"$Node\"})"
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\"^$Node$\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"^$Node$\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[2m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",node=~\"^$Node$\"}[2m])) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node=~\"^$Node$\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",node=~\"^$Node$\"}[2m])) by (node, name, image)",
       "legendFormat": "docker: {{ node }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",node=~\"^$Node$\"}[2m])) by (node, rkt_container_name)",
       "legendFormat": "rkt: {{ node }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",node=~\"^$Node$\"}[2m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",node=~\"^$Node$\"}) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node=~\"^$Node$\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",node=~\"^$Node$\"}) by (node, name, image)",
       "legendFormat": "docker: {{ node }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",node=~\"^$Node$\"}) by (node, rkt_container_name)",
       "legendFormat": "rkt: {{ node }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",node=~\"^$Node$\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[2m])) by (pod_name)",
       "legendFormat": "-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[2m])) by (pod_name)",
       "legendFormat": "<- {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",node=~\"^$Node$\"}[2m])) by (node, name, image)",
       "legendFormat": "-> docker: {{ node }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",node=~\"^$Node$\"}[2m])) by (node, name, image)",
       "legendFormat": "<- docker: {{ node }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",node=~\"^$Node$\"}[2m])) by (node, rkt_container_name)",
       "legendFormat": "-> rkt: {{ node }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",node=~\"^$Node$\"}[2m])) by (node, rkt_container_name)",
       "legendFormat": "<- rkt: {{ node }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",node=~\"^$Node$\"}[2m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",node=~\"^$Node$\"}[2m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  }
 ]
}