{
 "title": "Prometheus Stats",
 "description": "Metrics useful for Prometheus itself.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "query_result(prometheus_tsdb_head_samples_appended_total)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(up{job=~\"$job\"})"
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$job\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$job\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "5m"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes_total{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "HTTP Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(prometheus_http_request_duration_seconds_bucket{handler=~\"/api/.*|/-/.*|/metrics\", job=\"$job\", namespace=\"$namespace\"}[5m])) by (handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(prometheus_http_response_size_bytes_bucket{handler=~\"/api/.*|/-/.*|/metrics\", job=\"$job\", namespace=\"$namespace\"}[5m])) by (handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "Open"
    }
   ]
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Samples Appended",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"$job\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "Ingested"
    }
   ]
  },
  {
   "title": "Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(prometheus_tsdb_head_series_created_total{job=\"$job\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "Created"
    },
    {
     "expr": "increase(prometheus_tsdb_head_series_removed_total{job=\"$job\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "round(increase(prometheus_tsdb_head_chunks_created_total{job=\"$job\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Created"
    },
    {
     "expr": "round(increase(prometheus_tsdb_head_chunks_removed_total{job=\"$job\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Head Time Range",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_min_time{job=\"$job\", namespace=\"$namespace\"}",
       "legendFormat": "Min"
      },
      { "expr": "time() * 1000", "legendFormat": "Now" },
      {
       "expr": "prometheus_tsdb_head_max_time{job=\"$job\", namespace=\"$namespace\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "TSDB Reloads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(increase(prometheus_tsdb_reloads_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Reloads"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Time Range",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "round(histogram_quantile(0.90, sum(increase(prometheus_tsdb_compaction_chunk_range_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[10m])) by (le)))",
       "legendFormat": "Avg Chunk Time Range"
      }
     ]
    },
    {
     "title": "Head GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_gc_duration_seconds{job=\"$job\", namespace=\"$namespace\", quantile!=\"0.01\", quantile!=\"0.05\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "TSDB Compactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "round(increase(prometheus_tsdb_compactions_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Compactions"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Samples",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "round(histogram_quantile(0.90, sum(increase(prometheus_tsdb_compaction_chunk_samples_bucket{job=\"$job\", namespace=\"$namespace\"}[10m])) by (le)))",
       "legendFormat": "Chunk Samples"
      }
     ]
    },
    {
     "title": "Compaction Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{job=\"$job\", namespace=\"$namespace\"}[10m]) / rate(prometheus_tsdb_compaction_duration_seconds_count{job=\"$job\", namespace=\"$namespace\"}[10m])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "TSDB Retention Cutoffs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "round(increase(prometheus_tsdb_time_retentions_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Time Cutoffs"
      },
      {
       "expr": "round(increase(prometheus_tsdb_size_retentions_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Size Cutoffs"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Bytes/Sample",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "round(histogram_quantile(0.90, sum(rate(prometheus_tsdb_compaction_chunk_size_bytes_bucket{job=\"$job\", namespace=\"$namespace\"}[10m])) by (le)))",
       "legendFormat": "Bytes/Sample"
      }
     ]
    },
    {
     "title": "WAL Fsync&Truncate Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_wal_fsync_duration_seconds{job=\"$job\", namespace=\"$namespace\", quantile!=\"0.01\", quantile!=\"0.05\"}",
       "legendFormat": "Fsync ({{quantile}})"
      },
      {
       "expr": "prometheus_tsdb_wal_truncate_duration_seconds{job=\"$job\", namespace=\"$namespace\", quantile!=\"0.99\", quantile!=\"0.05\"}",
       "legendFormat": "Truncate ({{quantile}})"
      }
     ]
    },
    {
     "title": "TSDB Problems",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "round(increase(prometheus_tsdb_wal_corruptions_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "WAL Corruptions"
      },
      {
       "expr": "round(increase(prometheus_tsdb_reloads_failures_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Reload Failures"
      },
      {
       "expr": "round(increase(prometheus_tsdb_head_series_not_found_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Head Series Not Found"
      },
      {
       "expr": "round(increase(prometheus_tsdb_compactions_failed_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Compaction Failures"
      },
      {
       "expr": "round(increase(prometheus_tsdb_retention_cutoffs_failures_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Retention Cutoff Failures"
      },
      {
       "expr": "round(increase(prometheus_tsdb_checkpoint_creations_failed_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "WAL Checkpoint Creation Failures"
      },
      {
       "expr": "round(increase(prometheus_tsdb_checkpoint_deletions_failed_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "WAL Checkpoint Deletion Failures"
      }
     ]
    },
    {
     "title": "Blocks Loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_blocks_loaded{job=\"$job\", namespace=\"$namespace\"}",
       "legendFormat": "Blocks Loaded"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Engine",
     "type": "graph",
     "description": "Time spent in each mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"$job\", namespace=\"$namespace\"}[1m])",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Rule Group Evaluation Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_rule_group_duration_seconds{job=\"$job\", namespace=\"$namespace\", quantile!=\"0.01\", quantile!=\"0.05\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Rule Group Evaluation Problem",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(increase(prometheus_rule_group_iterations_missed_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Missed"
      },
      {
       "expr": "round(increase(prometheus_rule_evaluation_failures_total{job=\"$job\", namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  }
 ]
}