apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "log-aggregator.fullname" . }}
  labels:
    app: {{ template "log-aggregator.name" . }}
    chart: {{ template "log-aggregator.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
