- job_name: 'prometheus-io-scrape'
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - ingress-nginx
      - ingress-controller
      - kube-system
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
    action: replace
    target_label: __scheme__
    regex: (https?)
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
  - source_labels: [__meta_kubernetes_pod_node_name]
    action: replace
    target_label: node
    regex: (.+)
    replacement: $1
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: namespace
    regex: (.+)
    replacement: $1
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: pod
    regex: (.+)
    replacement: $1
  - source_labels: [__meta_kubernetes_pod_ip]
    action: replace
    target_label: pod_ip
    regex: (.+)
    replacement: $1
  - source_labels: [__meta_kubernetes_pod_host_ip]
    action: replace
    target_label: host_ip
    regex: (.+)
    replacement: $1
  - source_labels: [__meta_kubernetes_pod_controller_kind]
    action: replace
    target_label: created_by_kind
    regex: (.+)
    replacement: $1
  - source_labels: [__meta_kubernetes_pod_controller_name]
    action: replace
    target_label: created_by_kind
    regex: (.+)
    replacement: $1