{{- if not .Values.configFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}
data:
  alertmanager.yaml: {{ toYaml .Values.config | b64enc | quote }}
{{- range $key, $val := .Values.templates }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
