apiVersion: {{ template "deployment_api_version" . }}
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: kube-state
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 8080
        - name: http-metrics
          containerPort: 8081
        livenessProbe:
{{ merge .Values.livenessProbe .Values.defaultLivenessProbe | toYaml | indent 10 }}
        readinessProbe:
{{ merge .Values.readinessProbe .Values.defaultReadinessProbe | toYaml | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      {{- if .Values.enabledRBAC }}
      serviceAccountName: {{ default (include "app.fullname" .) .Values.serviceAccountName }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      tolerations:
{{- include "linux-node-tolerations" . | nindent 8}}
      {{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      nodeSelector:
{{- include "linux-node-selector" . | nindent 8 }}
        {{- range .Values.nodeSelectors }}
        {{- $pair := regexSplit "=" . 2 }}
        {{- if eq 2 (len $pair) }}
        {{ (index $pair 0) }}: {{ (index $pair 1) }}
        {{- else }}
        {{ (index $pair 0) }}: ""
        {{- end }}
        {{- end }}
