{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
  name: compatible-v116-deprecated-metrics
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: workqueue_depth.rules
    rules:
    - record: APIServiceOpenAPIAggregationControllerQueue1_depth
      expr: workqueue_depth{name="APIServiceOpenAPIAggregationControllerQueue1"}
    - record: APIServiceRegistrationController_depth
      expr: workqueue_depth{name="APIServiceRegistrationController"}
    - record: AvailableConditionController_depth
      expr: workqueue_depth{name="AvailableConditionController"}
    - record: DiscoveryController_depth
      expr: workqueue_depth{name="DiscoveryController"}
    - record: admission_quota_controller_depth
      expr: workqueue_depth{name="admission_quota_controller"}
    - record: autoregister_depth
      expr: workqueue_depth{name="autoregister"}
    - record: crdEstablishing_depth
      expr: workqueue_depth{name="crdEstablishing"}
    - record: crd_autoregistration_controller_depth
      expr: workqueue_depth{name="crd_autoregistration_controller"}
    - record: crd_finalizer_depth
      expr: workqueue_depth{name="crd_finalizer"}
    - record: crd_naming_condition_controller_depth
      expr: workqueue_depth{name="crd_naming_condition_controller"}
    - record: crd_openapi_controller_depth
      expr: workqueue_depth{name="crd_openapi_controller"}
    - record: kubernetes_api_approval_conformant_condition_controller_depth
      expr: workqueue_depth{name="kubernetes_api_approval_conformant_condition_controller"}
    - record: non_structural_schema_condition_controller_depth
      expr: workqueue_depth{name="non_structural_schema_condition_controller"}
    - record: ClusterRoleAggregator_depth
      expr: workqueue_depth{name="ClusterRoleAggregator"}
    - record: certificate_depth
      expr: workqueue_depth{name="certificate"}
    - record: claims_depth
      expr: workqueue_depth{name="claims"}
    - record: disruption_depth
      expr: workqueue_depth{name="disruption"}
    - record: disruption_recheck_depth
      expr: workqueue_depth{name="disruption_recheck_depth"}
    - record: garbage_collector_attempt_to_delete_depth
      expr: workqueue_depth{name="garbage_collector_attempt_to_delete"}
    - record: garbage_collector_attempt_to_orphan_depth
      expr: workqueue_depth{name="garbage_collector_attempt_to_orphan"}
    - record: garbage_collector_graph_changes_depth
      expr: workqueue_depth{name="garbage_collector_graph_changes"}
    - record: horizontalpodautoscaler_depth
      expr: workqueue_depth{name="horizontalpodautoscaler"}
    - record: node_lifecycle_controller_depth
      expr: workqueue_depth{name="node_lifecycle_controller"}
    - record: noexec_taint_node_depth
      expr: workqueue_depth{name="noexec_taint_node"}
    - record: noexec_taint_pod_depth
      expr: workqueue_depth{name="noexec_taint_pod"}
    - record: pvcprotection_depth
      expr: workqueue_depth{name="pvcprotection"}
    - record: pvcs_depth
      expr: workqueue_depth{name="pvcs"}
    - record: pvprotection_depth
      expr: workqueue_depth{name="pvprotection"}
    - record: resource_quota_controller_resource_changes_depth
      expr: workqueue_depth{name="resource_quota_controller_resource_changes"}
    - record: resourcequota_primary_depth
      expr: workqueue_depth{name="resourcequota_primary"}
    - record: resourcequota_priority_depth
      expr: workqueue_depth{name="resourcequota_priority"}
    - record: serviceaccount_tokens_secret_depth
      expr: workqueue_depth{name="serviceaccount_tokens_secret"}
    - record: serviceaccount_tokens_service_depth
      expr: workqueue_depth{name="serviceaccount_tokens_service"}
    - record: volume_expand_depth
      expr: workqueue_depth{name="volume_expand"}
    - record: ttlcontroller_depth
      expr: workqueue_depth{name="ttlcontroller"}
    - record: volumes_depth
      expr: workqueue_depth{name="volumes"}
    - record: deployment_depth
      expr: workqueue_depth{name="deployment"}
    - record: replicaset_depth
      expr: workqueue_depth{name="replicaset"}
    - record: service_depth
      expr: workqueue_depth{name="service"}
    - record: serviceaccount_depth
      expr: workqueue_depth{name="serviceaccount"}
    - record: endpoint_depth
      expr: workqueue_depth{name="endpoint"}
    - record: daemonset_depth
      expr: workqueue_depth{name="daemonset"}
    - record: statefulset_depth
      expr: workqueue_depth{name="statefulset"}
    - record: replicationmanager_depth
      expr: workqueue_depth{name="replicationmanager"}
    - record: job_depth
      expr: workqueue_depth{name="job"}
    - record: namespace_depth
      expr: workqueue_depth{name="namespace"}
{{- end }}
